name: Get Vault Secrets
description: Composite action (step) to get secrets from Grafana Labs' Vault instance.
inputs:
  workload_identity_provider:
    required: true
    description: Set to `secrets.WORKLOAD_IDENTITY_POOL_PROVIDER`
  iap_service_account:
    required: true
    description: Set to `secrets.VAULT_IAP_SA_EMAIL`
  iap_audience:
    required: true
    description: Set to `secrets.VAULT_IAP_OAUTH_CLIENT_ID`
  vault_url:
    required: true
    description: Set to `secrets.VAULT_URL`
  secrets:
    required: true
    description: Secret mapping. See https://github.com/hashicorp/vault-action for the format.

runs: 
  using: composite
  steps:
    - id: vault-iap-auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "${{ inputs.workload_identity_provider }}"
        service_account: "${{ inputs.iap_service_account }}"
        token_format: id_token
        id_token_audience: "${{ inputs.iap_audience }}"
        id_token_include_email: true

      # Get the secrets
    - name: Import Secrets
      id: import-secrets
      uses: hashicorp/vault-action@v2
      with:
        url: "${{ inputs.vault_url }}"
        role: vault-github-actions
        path: github-actions-oidc
        method: jwt
        jwtGithubAudience: "${{ inputs.vault_url }}"
        extraHeaders: |
          Proxy-Authorization: Bearer ${{ steps.vault-iap-auth.outputs.id_token }}
        secrets: |
          ${{ inputs.secrets }}

