name: Test get-vault-secrets action

on:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    strategy:
      matrix:
        instance:
          - dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Test Vault Action
        id: test-vault-action
        uses: ./actions/get-vault-secrets
        continue-on-error: true
        with:
          vault_instance: ${{ matrix.instance }}
          repo_secrets: |
            INSTANCE=test-get-vault-secret:instance

      - name: Check secret value is ${{ matrix.instance }}
        if: matrix.instance != 'invalid'
        run: |
          if [[ "${{ env.INSTANCE }}" != "${{ matrix.instance }}" ]]; then
            echo "Test failed: secret value does not match vault_instance input"
            exit 1
          fi
